import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, AlertTriangle, Calendar, Target, Clock, DollarSign, TrendingUp, FileText, Shield, Eye, SkipForward } from 'lucide-react';
import { Stars } from '@/components/cosmic/Stars';
import { Aurora } from '@/components/cosmic/Aurora';
import { AnimateOnScroll, StaggerChildren } from '@/components/motion';
import { PrintButton } from '@/components/ui/PrintButton';

export const metadata: Metadata = {
  title: 'Grant Intelligence Scan — Valencia College | Wavelength',
  description:
    'Live Grant Intelligence Scan for Valencia College. 20 federal grants reviewed, 2 priority opportunities identified totaling $130M+ in available funding. Generated by live pipeline February 2026.',
  alternates: { canonical: 'https://withwavelength.com/report/valencia-grant-scan' },
  openGraph: {
    title: 'Grant Intelligence Scan — Valencia College',
    description:
      '20 federal grants reviewed. 2 priority, 5 strategic, 8 monitor, 5 skip. $130M+ in available funding across top opportunities. Live pipeline data.',
    url: 'https://withwavelength.com/report/valencia-grant-scan',
    type: 'article',
  },
};

// ─── Helper Components ────────────────────────────────────────────────────────

function ScoreBar({ score, max = 10, color = 'purple' }: { score: number; max?: number; color?: string }) {
  const pct = (score / max) * 100;
  const gradients: Record<string, string> = {
    purple: 'linear-gradient(90deg, #a855f7, #6366f1)',
    teal: 'linear-gradient(90deg, #14b8a6, #0ea5e9)',
    amber: 'linear-gradient(90deg, #f59e0b, #f97316)',
    rose: 'linear-gradient(90deg, #f43f5e, #e11d48)',
  };
  return (
    <div className="w-full h-2 rounded-full bg-theme-surface overflow-hidden">
      <div
        className="h-full rounded-full transition-all"
        style={{ width: `${pct}%`, background: gradients[color] ?? gradients.purple }}
      />
    </div>
  );
}

function TierBadge({ tier }: { tier: string }) {
  const map: Record<string, { cls: string; label: string }> = {
    priority: { cls: 'bg-rose-500/10 text-rose-700 dark:text-rose-400 border border-rose-500/20', label: '🎯 PRIORITY' },
    strategic: { cls: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border border-amber-500/20', label: '📋 STRATEGIC' },
    monitor: { cls: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border border-blue-500/20', label: '👁 MONITOR' },
    skip: { cls: 'bg-gray-500/10 text-gray-600 dark:text-gray-400 border border-gray-500/20', label: '⏭ SKIP' },
  };
  const m = map[tier] ?? map.monitor;
  return <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${m.cls}`}>{m.label}</span>;
}

function EffortBadge({ level }: { level: string }) {
  const map: Record<string, string> = {
    heavy: 'bg-rose-500/10 text-rose-700 dark:text-rose-400 border border-rose-500/20',
    moderate: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border border-amber-500/20',
    light: 'bg-teal-500/10 text-teal-700 dark:text-teal-400 border border-teal-500/20',
  };
  return <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${map[level] ?? map.heavy}`}>🔴 {level.toUpperCase()} (80-120 hrs)</span>;
}

// ─── Real Pipeline Data (Generated 2026-02-19 via live grant-scan pipeline) ──

const scanMeta = {
  totalReviewed: 20,
  priority: 2,
  strategic: 5,
  monitor: 8,
  skip: 5,
  generatedAt: 'February 19, 2026',
  topFunding: '$130M+',
};

const priorityGrants = [
  {
    title: 'Strengthening Community Colleges Training Grants (Round 6)',
    agency: 'Employment and Training Administration (U.S. Department of Labor)',
    agencyCode: 'DOL-ETA',
    cfda: '17.280',
    score: 8.7,
    scores: { eligibility: 10, alignment: 10, awardSize: 8, competition: 4, timeline: 10 },
    scoreRationale: {
      eligibility: 'Community colleges explicitly eligible; Valencia meets all requirements.',
      alignment: 'Perfect match to workforce development mission and existing programs.',
      awardSize: 'Substantial funding: $65M total, typical awards $1-3M over 3-4 years.',
      competition: 'Highly competitive national pool; Round 6 suggests experienced applicants.',
      timeline: '90 days provides adequate preparation time for comprehensive proposal.',
    },
    tier: 'priority',
    deadline: 'May 20, 2026',
    daysRemaining: 90,
    totalFunding: '$65 million',
    estimatedAward: '$1-3M (over 3-4 years)',
    matchRequired: '0-25% (historically encouraged, not required)',
    effortLevel: 'heavy',
    effortHours: '80-120 hours',
    url: 'https://www.grants.gov/search-results-detail/361307',
    whyItFits: 'Valencia College is an excellent candidate given near-perfect alignment between the program\'s workforce training focus and Valencia\'s strategic priorities in career technical education. The college\'s existing programs in healthcare, IT/cybersecurity, hospitality, and advanced manufacturing directly match ETA priorities. Valencia should consider forming a consortium with other Florida community colleges to strengthen competitiveness.',
    narrativeSections: [
      'Project Abstract/Summary',
      'Statement of Need (regional labor market analysis, skills gaps)',
      'Project Design and Implementation Plan',
      'Organizational Capacity and Key Personnel',
      'Partnerships and Collaboration',
      'Sustainability Plan',
      'Evaluation and Performance Measurement Plan',
      'Budget Narrative',
    ],
    dataNeeded: [
      'Current enrollment data by program/CIP code',
      'Student demographic data (low-income, minorities, veterans, displaced workers)',
      'Program completion and credential attainment rates',
      'Employment outcomes and wage data (6-month and 12-month)',
      'Regional labor market analysis with demand projections',
      'Employer engagement documentation (advisory boards, internships, hiring commitments)',
    ],
    lettersRequired: [
      '3-5 employer partners documenting hiring needs and training requirements',
      'Local Workforce Development Board letter confirming alignment',
      'State workforce agency or Florida College System endorsement',
      'Industry associations or sector partnerships',
      'Community-based organizations serving target populations',
    ],
    pastAwards: 'Round 6 of established program. $65M total funding. Consortiums of higher education institutions welcomed. Successful proposals demonstrate: strong workforce training capacity, measurable employment and wage outcomes, robust employer engagement, and sustainability planning.',
  },
  {
    title: 'Advanced Technological Education (ATE)',
    agency: 'U.S. National Science Foundation',
    agencyCode: 'NSF',
    cfda: '47.076',
    score: 8.4,
    scores: { eligibility: 10, alignment: 9, awardSize: 7, competition: 5, timeline: 10 },
    scoreRationale: {
      eligibility: 'Two-year community colleges are primary target audience; Valencia fully eligible.',
      alignment: 'Strong match to IT/cybersecurity, healthcare tech, and advanced manufacturing.',
      awardSize: 'Moderate awards ($300K-$900K) support significant program development.',
      competition: 'Competitive but community colleges prioritized; strong proposals succeed.',
      timeline: '224 days provides excellent preparation time.',
    },
    tier: 'priority',
    deadline: 'October 1, 2026',
    daysRemaining: 224,
    totalFunding: '$69 million (FY 2025)',
    estimatedAward: '$300K-$900K (3-year project)',
    matchRequired: 'Not required (voluntary cost share accepted)',
    effortLevel: 'heavy',
    effortHours: '80-120 hours',
    url: 'https://www.grants.gov/search-results-detail/355100',
    whyItFits: 'NSF ATE explicitly prioritizes two-year community colleges as the program\'s core constituency. Valencia\'s IT/cybersecurity, healthcare technology, and advanced manufacturing programs directly align with ATE\'s STEM technician workforce focus. Orlando provides access to robust industry partnerships in technology, healthcare, and defense.',
    narrativeSections: [
      'Project Summary (1-page)',
      'Project Description (15-page limit)',
      'Intellectual Merit section',
      'Broader Impacts section',
      'Results from Prior NSF Support (if applicable)',
      'Project Evaluation Plan',
      'Sustainability Plan',
      'Management Plan',
      'Budget Narrative',
    ],
    dataNeeded: [
      'Current enrollment data by program/CIP code for STEM/technical programs',
      'Student demographic data showing diversity in STEM',
      'Program completion and retention rates',
      'Graduate employment and placement data with wages',
      'Regional labor market demand for technician occupations',
      'Faculty qualifications and industry certifications',
      'Data management plan (NSF requirement)',
    ],
    lettersRequired: [
      '3-5 industry/employer partners documenting workforce needs',
      'Four-year university transfer partners for articulation pathways',
      'Regional workforce development boards confirming alignment',
      'Professional associations or industry groups',
      'Secondary education partners (if K-12 pipeline included)',
    ],
    pastAwards: 'Past recipients include Wallace Community College, Lorain County CC, Los Angeles Mission College. $69M in FY 2025 across multiple awards. Priorities: innovative technician education, industry partnerships, intellectual merit + broader impacts, diversity, replicability.',
  },
];

const strategicGrants = [
  {
    title: 'Next Gen STEM (NGS) NASA Aerospace Skilled Technical Workforce Hubs',
    agency: 'National Aeronautics and Space Administration',
    cfda: '43.008',
    score: 7.0,
    tier: 'strategic',
    deadline: 'March 20, 2026',
    daysRemaining: 29,
    estimatedAward: 'Up to $1,500,000',
    url: 'https://www.grants.gov/search-results-detail/361254',
    keyNote: '29-day timeline is extremely challenging. GO/NO-GO decision needed within 5-7 days. Only pursue if undocumented aerospace relationships already exist. Recommend skip this cycle.',
    scores: { eligibility: 10, alignment: 4, awardSize: 10, competition: 4, timeline: 4 },
  },
  {
    title: 'Garrett Lee Smith Campus Suicide Prevention',
    agency: 'SAMHSA (HHS)',
    cfda: '93.243',
    score: 6.6,
    tier: 'strategic',
    deadline: 'Unknown',
    daysRemaining: null,
    estimatedAward: '$250K-$350K (3 years)',
    url: 'https://www.grants.gov/search-results-detail/360972',
    keyNote: 'Unknown deadline is critical barrier. Not explicitly aligned with strategic plan but supports student success. Monitor SAMHSA announcements for next cycle.',
    scores: { eligibility: 9, alignment: 6, awardSize: 7, competition: 6, timeline: 1 },
  },
  {
    title: 'MSIPP Consortia Grant Program (NNSA)',
    agency: 'National Nuclear Security Administration (DOE)',
    cfda: '81.123',
    score: 6.5,
    tier: 'strategic',
    deadline: 'June 15, 2026',
    daysRemaining: 116,
    estimatedAward: '$500K-$1.5M (3-5 years)',
    url: 'https://www.grants.gov/search-results-detail/351714',
    keyNote: 'Requires consortium of Minority-Serving Institutions. Valencia likely qualifies as HSI. Cybersecurity aligns with NNSA mission. Partner with Miami Dade, FIU, or Broward College.',
    scores: { eligibility: 8, alignment: 6, awardSize: 5, competition: 4, timeline: 10 },
  },
  {
    title: 'NDEP STEM Open NFO',
    agency: 'Washington Headquarters Services (DoD)',
    cfda: '12.006',
    score: 6.4,
    tier: 'strategic',
    deadline: 'February 8, 2028',
    daysRemaining: 719,
    estimatedAward: 'Unknown',
    url: 'https://www.grants.gov/search-results-detail/345938',
    keyNote: 'Extended timeline (719 days) for strategic planning. Community college eligibility unclear — needs investigation. Strong STEM alignment through cybersecurity and advanced manufacturing.',
    scores: { eligibility: 6, alignment: 8, awardSize: 5, competition: 4, timeline: 10 },
  },
  {
    title: 'ONR STEM Education and Workforce Program',
    agency: 'Office of Naval Research (U.S. Navy)',
    cfda: '12.330',
    score: 6.2,
    tier: 'strategic',
    deadline: 'June 30, 2026',
    daysRemaining: 131,
    estimatedAward: 'Unknown',
    url: 'https://www.grants.gov/search-results-detail/359932',
    keyNote: 'Naval Air Warfare Center Training Systems Division (NAWCTSD) is located in Orlando — critical partnership opportunity. Cybersecurity and advanced manufacturing align with naval workforce needs.',
    scores: { eligibility: 7, alignment: 6, awardSize: 5, competition: 4, timeline: 10 },
  },
];

const monitorGrants = [
  { title: 'NIGMS Biomedical Undergraduate Research Training (BURT)', agency: 'NIH', score: 5.3, deadline: 'Sep 25, 2028', note: 'Worth monitoring if Valencia develops research partnerships with biomedical institutions.' },
  { title: 'Louis Stokes Alliances for Minority Participation (LSAMP)', agency: 'NSF', score: 5.2, deadline: 'Nov 20, 2026', note: 'Track for potential participation as alliance partner (not lead) with four-year institutions.' },
  { title: 'National Space Grant College and Fellowship Program', agency: 'NASA', score: 5.0, deadline: 'TBD', note: 'Orlando proximity to Kennedy Space Center could be strategic if aerospace programs develop.' },
  { title: 'Mathematical Sciences Infrastructure Program', agency: 'NSF', score: 4.7, deadline: 'Aug 4, 2026', note: 'Low priority — focuses on mathematical sciences research rather than applied workforce training.' },
  { title: 'ECosystem for Leading Innovation in Plasma Science (ECLIPSE)', agency: 'NSF', score: 4.6, deadline: 'Aug 11, 2026', note: 'Not aligned with mission. Track only for potential subcontract role.' },
  { title: 'TURTLE Program (T34)', agency: 'NIH', score: 4.6, deadline: 'Jan 25, 2027', note: 'Not applicable — Valencia is not a Tribal institution.' },
  { title: 'Research in the Formation of Engineers', agency: 'NSF', score: 4.5, deadline: 'TBD', note: 'Low priority given lack of engineering degree programs.' },
  { title: 'Community-Partnered Nursing Research Centers', agency: 'NIH', score: 4.5, deadline: 'TBD', note: 'Targets research-intensive nursing schools with doctoral programs — not community colleges.' },
];

const skipGrants = [
  { title: 'Atmosphere Cluster', agency: 'NSF', score: 3.8, reason: 'Fundamental atmospheric science research — no connection to workforce programs.' },
  { title: 'Tribal Colleges and Universities Program', agency: 'NSF', score: 3.7, reason: 'Valencia is not a Tribal institution and is ineligible.' },
  { title: 'TURTLE Program (T32)', agency: 'NIH', score: 3.7, reason: 'Explicitly designed for Tribal institutions; Valencia ineligible.' },
  { title: 'Geospace Cluster', agency: 'NSF', score: 3.1, reason: 'Advanced geospace sciences research — outside institutional capacity.' },
  { title: 'LPS Qubit Collaboratory', agency: 'Dept of the Army', score: 2.8, reason: 'Quantum computing research — completely outside program portfolio.' },
];

const deadlineCalendar = [
  { month: 'Mar 2026', grant: 'Next Gen STEM NASA Aerospace Hubs', deadline: 'March 20, 2026', tier: 'strategic', daysRemaining: 29, action: 'Assess aerospace partnerships; likely skip this cycle' },
  { month: 'May 2026', grant: 'Strengthening Community Colleges Training Grants (Round 6)', deadline: 'May 20, 2026', tier: 'priority', daysRemaining: 90, action: 'Begin immediately; form consortium' },
  { month: 'Jun 2026', grant: 'MSIPP Consortia Grant Program', deadline: 'June 15, 2026', tier: 'strategic', daysRemaining: 116, action: 'Identify consortium partners; confirm HSI status' },
  { month: 'Jun 2026', grant: 'ONR STEM Education and Workforce', deadline: 'June 30, 2026', tier: 'strategic', daysRemaining: 131, action: 'Develop NAWCTSD partnership' },
  { month: 'Oct 2026', grant: 'Advanced Technological Education (NSF ATE)', deadline: 'October 1, 2026', tier: 'priority', daysRemaining: 224, action: 'Develop industry partnerships; select program focus' },
  { month: 'Feb 2028', grant: 'NDEP STEM Open NFO', deadline: 'February 8, 2028', tier: 'strategic', daysRemaining: 719, action: 'Clarify eligibility; develop defense partnerships' },
  { month: 'TBD', grant: 'Garrett Lee Smith Campus Suicide Prevention', deadline: 'Unknown', tier: 'strategic', daysRemaining: null, action: 'Monitor SAMHSA announcements' },
];

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function ValenciaGrantScanPage() {
  return (
    <div className="overflow-x-hidden bg-theme-page">
      {/* ═══════════ A. HERO ═══════════ */}
      <section className="relative min-h-[60vh] flex items-center justify-center pt-32 lg:pt-36 pb-16">
        <Stars count={120} />
        <Aurora className="opacity-60" />

        <div className="relative z-10 max-w-[1200px] mx-auto px-6 text-center">
          <AnimateOnScroll variant="fade-up" duration={800}>
            <span className="overline">Grant Intelligence Scan · Live Report</span>
          </AnimateOnScroll>

          <AnimateOnScroll variant="fade-up" delay={100} duration={800}>
            <h1
              className="font-heading font-bold text-gradient-cosmic leading-[1.05] mx-auto max-w-4xl mt-4"
              style={{ fontSize: 'clamp(2.5rem, 5vw + 0.5rem, 4rem)' }}
            >
              Valencia College
            </h1>
          </AnimateOnScroll>

          <AnimateOnScroll variant="fade-up" delay={180} duration={800}>
            <p className="mt-4 text-lg text-theme-secondary">
              Orlando, Florida · Federal Grant Landscape · February 2026
            </p>
          </AnimateOnScroll>

          {/* Stat Pills */}
          <AnimateOnScroll variant="fade-up" delay={260} duration={800}>
            <div className="mt-7 flex flex-wrap items-center justify-center gap-3">
              <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-600 dark:text-purple-400 font-semibold text-sm">
                <span className="w-2 h-2 rounded-full bg-purple-500" />
                20 Grants Reviewed
              </span>
              <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-rose-500/10 border border-rose-500/20 text-rose-700 dark:text-rose-400 font-semibold text-sm">
                <span className="w-2 h-2 rounded-full bg-rose-500" />
                2 Priority Opportunities
              </span>
              <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-700 dark:text-amber-400 font-semibold text-sm">
                <span className="w-2 h-2 rounded-full bg-amber-500" />
                5 Strategic Grants
              </span>
              <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-teal-500/10 border border-teal-500/20 text-teal-600 dark:text-teal-400 font-semibold text-sm">
                <span className="w-2 h-2 rounded-full bg-teal-500" />
                $130M+ Available Funding
              </span>
            </div>
          </AnimateOnScroll>

          <AnimateOnScroll variant="fade-up" delay={340} duration={800}>
            <div className="mt-6 flex justify-center">
              <PrintButton />
            </div>
          </AnimateOnScroll>
        </div>
      </section>

      {/* ═══════════ B. TIER DISTRIBUTION ═══════════ */}
      <section className="relative py-16 md:py-24 print:py-10">
        <div className="max-w-[1200px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <div className="text-center mb-12">
              <span className="overline">Grant Landscape Overview</span>
              <h2
                className="font-heading font-bold text-theme-primary mt-3"
                style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.5rem)' }}
              >
                20 federal grants scored and tiered
              </h2>
            </div>
          </AnimateOnScroll>

          <AnimateOnScroll variant="fade-up" delay={80}>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {[
                { tier: 'Priority', count: scanMeta.priority, color: 'rose', icon: '🎯', desc: 'Pursue immediately — high fit, strong funding' },
                { tier: 'Strategic', count: scanMeta.strategic, color: 'amber', icon: '📋', desc: 'Plan ahead — good fit, needs partnership development' },
                { tier: 'Monitor', count: scanMeta.monitor, color: 'blue', icon: '👁', desc: 'Track for future cycles — moderate alignment' },
                { tier: 'Skip', count: scanMeta.skip, color: 'gray', icon: '⏭', desc: 'Not aligned — ineligible or poor fit' },
              ].map((t) => (
                <div key={t.tier} className="card-cosmic rounded-2xl p-6 text-center">
                  <span className="text-3xl">{t.icon}</span>
                  <p className="text-4xl font-bold font-mono text-theme-primary mt-3">{t.count}</p>
                  <p className={`text-sm font-bold mt-1 ${
                    t.color === 'rose' ? 'text-rose-600 dark:text-rose-400'
                    : t.color === 'amber' ? 'text-amber-600 dark:text-amber-400'
                    : t.color === 'blue' ? 'text-blue-600 dark:text-blue-400'
                    : 'text-gray-500'
                  }`}>{t.tier}</p>
                  <p className="text-xs text-theme-muted mt-2">{t.desc}</p>
                </div>
              ))}
            </div>
          </AnimateOnScroll>
        </div>
      </section>

      {/* ═══════════ C. EXECUTIVE SUMMARY ═══════════ */}
      <section className="relative py-16 md:py-20 bg-theme-surface/30 print:py-8">
        <div className="max-w-[900px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <span className="overline block text-center mb-3">Executive Summary</span>
            <h2
              className="font-heading font-bold text-theme-primary text-center mb-8"
              style={{ fontSize: 'clamp(1.5rem, 2.5vw + 0.5rem, 2.25rem)' }}
            >
              What This Scan Found
            </h2>
          </AnimateOnScroll>

          <AnimateOnScroll variant="fade-up" delay={80}>
            <div className="space-y-5 text-theme-secondary leading-relaxed">
              <p>
                Valencia College has <strong>two exceptional federal grant opportunities</strong> totaling an estimated <strong>$130+ million in available funding</strong> that align nearly perfectly with the institution&apos;s workforce development mission and existing program strengths.
              </p>
              <p>
                The <strong>Strengthening Community Colleges Training Grants (Round 6)</strong> from the Employment and Training Administration (deadline May 20, 2026) and the <strong>Advanced Technological Education</strong> program from NSF (deadline October 1, 2026) represent the highest-value targets, with fit scores of <strong>8.7/10</strong> and <strong>8.4/10</strong> respectively. Both programs explicitly prioritize community colleges and directly support Valencia&apos;s strategic priorities in healthcare, IT/cybersecurity, hospitality, and advanced manufacturing.
              </p>
              <p>
                Beyond these priority opportunities, five strategic grants merit planning attention, though several require significant partnership development or represent departures from Valencia&apos;s core mission. The overall federal landscape <strong>strongly favors Valencia&apos;s institutional profile</strong> as a comprehensive community college with established career-technical programs, particularly in the current policy environment emphasizing workforce development and skilled technical training.
              </p>
            </div>
          </AnimateOnScroll>

          {/* Key Findings Strip */}
          <AnimateOnScroll variant="fade-up" delay={160}>
            <div className="mt-10 grid sm:grid-cols-3 gap-4">
              <div className="rounded-xl p-5 bg-rose-500/5 border border-rose-500/15">
                <Target className="w-5 h-5 text-rose-500 mb-3" />
                <p className="text-sm font-bold text-theme-primary mb-1">Immediate Action</p>
                <p className="text-xs text-theme-secondary leading-relaxed">ETA Strengthening CC grants — 90-day deadline, $65M program, 8.7/10 fit score. Begin consortium development now.</p>
              </div>
              <div className="rounded-xl p-5 bg-purple-500/5 border border-purple-500/15">
                <TrendingUp className="w-5 h-5 text-purple-500 mb-3" />
                <p className="text-sm font-bold text-theme-primary mb-1">Strong Pipeline</p>
                <p className="text-xs text-theme-secondary leading-relaxed">NSF ATE ($69M program) due October 2026. 224 days to build industry partnerships and select program focus.</p>
              </div>
              <div className="rounded-xl p-5 bg-amber-500/5 border border-amber-500/15">
                <AlertTriangle className="w-5 h-5 text-amber-500 mb-3" />
                <p className="text-sm font-bold text-theme-primary mb-1">Proceed with Caution</p>
                <p className="text-xs text-theme-secondary leading-relaxed">NASA Aerospace Hub ($1.5M) has only 29 days remaining. Skip this cycle unless aerospace partnerships already exist.</p>
              </div>
            </div>
          </AnimateOnScroll>
        </div>
      </section>

      {/* ═══════════ D. PRIORITY GRANTS — DEEP DIVE ═══════════ */}
      <section className="relative py-16 md:py-24 print:py-10">
        <div className="max-w-[1200px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <div className="text-center mb-12">
              <span className="overline">Section D · Priority Grants — Pursue Immediately</span>
              <h2
                className="font-heading font-bold text-theme-primary mt-3"
                style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.5rem)' }}
              >
                2 Grants Scoring 8.0+ / 10
              </h2>
              <p className="mt-3 text-theme-secondary max-w-xl mx-auto text-sm">
                Full scoring breakdown, application requirements, competitive intelligence, and effort estimates for each priority opportunity.
              </p>
            </div>
          </AnimateOnScroll>

          <StaggerChildren stagger={100} variant="fade-up" className="space-y-8">
            {priorityGrants.map((grant) => (
              <div key={grant.title} className="card-cosmic rounded-2xl p-7 border-rose-500/20">
                {/* Header */}
                <div className="flex flex-wrap items-start justify-between gap-4 mb-6">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-2">
                      <TierBadge tier={grant.tier} />
                      <span className="text-xs font-mono text-theme-muted">CFDA {grant.cfda}</span>
                    </div>
                    <h3 className="font-heading font-bold text-xl text-theme-primary leading-snug">{grant.title}</h3>
                    <p className="text-sm text-theme-muted mt-1">{grant.agency}</p>
                  </div>
                  <div className="text-right flex-shrink-0">
                    <div
                      className="text-4xl font-bold font-mono"
                      style={{
                        background: 'linear-gradient(135deg, #f43f5e, #e11d48)',
                        WebkitBackgroundClip: 'text',
                        WebkitTextFillColor: 'transparent',
                      }}
                    >
                      {grant.score}
                    </div>
                    <p className="text-xs text-theme-muted">/ 10 fit score</p>
                  </div>
                </div>

                {/* Key Stats Row */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
                  <div className="rounded-lg p-3 bg-theme-surface/50 border border-theme-subtle text-center">
                    <Calendar className="w-4 h-4 text-rose-500 mx-auto mb-1" />
                    <p className="text-[10px] font-bold uppercase tracking-widest text-theme-muted mb-0.5">Deadline</p>
                    <p className="text-sm font-bold text-theme-primary">{grant.deadline}</p>
                    <p className="text-[10px] text-rose-600 dark:text-rose-400 font-semibold">{grant.daysRemaining} days</p>
                  </div>
                  <div className="rounded-lg p-3 bg-theme-surface/50 border border-theme-subtle text-center">
                    <DollarSign className="w-4 h-4 text-teal-500 mx-auto mb-1" />
                    <p className="text-[10px] font-bold uppercase tracking-widest text-theme-muted mb-0.5">Total Program</p>
                    <p className="text-sm font-bold text-teal-600 dark:text-teal-400">{grant.totalFunding}</p>
                  </div>
                  <div className="rounded-lg p-3 bg-theme-surface/50 border border-theme-subtle text-center">
                    <TrendingUp className="w-4 h-4 text-purple-500 mx-auto mb-1" />
                    <p className="text-[10px] font-bold uppercase tracking-widest text-theme-muted mb-0.5">Est. Award</p>
                    <p className="text-sm font-bold text-purple-600 dark:text-purple-400">{grant.estimatedAward}</p>
                  </div>
                  <div className="rounded-lg p-3 bg-theme-surface/50 border border-theme-subtle text-center">
                    <Shield className="w-4 h-4 text-amber-500 mx-auto mb-1" />
                    <p className="text-[10px] font-bold uppercase tracking-widest text-theme-muted mb-0.5">Match</p>
                    <p className="text-xs font-bold text-theme-primary">{grant.matchRequired}</p>
                  </div>
                </div>

                {/* Score Breakdown */}
                <div className="rounded-xl p-5 bg-theme-surface/30 border border-theme-subtle mb-6">
                  <p className="text-xs font-bold uppercase tracking-widest text-theme-muted mb-4">Scoring Breakdown</p>
                  <div className="space-y-3">
                    {[
                      { label: 'Eligibility Fit', score: grant.scores.eligibility, rationale: grant.scoreRationale.eligibility },
                      { label: 'Strategic Alignment', score: grant.scores.alignment, rationale: grant.scoreRationale.alignment },
                      { label: 'Award Size', score: grant.scores.awardSize, rationale: grant.scoreRationale.awardSize },
                      { label: 'Competition Level', score: grant.scores.competition, rationale: grant.scoreRationale.competition },
                      { label: 'Timeline Feasibility', score: grant.scores.timeline, rationale: grant.scoreRationale.timeline },
                    ].map((dim) => (
                      <div key={dim.label}>
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-xs font-semibold text-theme-primary">{dim.label}</span>
                          <span className="text-xs font-bold font-mono text-theme-secondary">{dim.score}/10</span>
                        </div>
                        <ScoreBar score={dim.score} color={dim.score >= 8 ? 'teal' : dim.score >= 5 ? 'amber' : 'rose'} />
                        <p className="text-[11px] text-theme-muted mt-1">{dim.rationale}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Why It Fits */}
                <div className="rounded-xl p-5 bg-purple-500/5 border border-purple-500/15 mb-6">
                  <p className="text-xs font-bold uppercase tracking-widest text-purple-600 dark:text-purple-400 mb-2">
                    Why This Fits Valencia College
                  </p>
                  <p className="text-sm text-theme-secondary leading-relaxed">{grant.whyItFits}</p>
                </div>

                {/* Two-column details */}
                <div className="grid md:grid-cols-2 gap-6 mb-6">
                  <div>
                    <p className="text-xs font-bold uppercase tracking-widest text-theme-muted mb-3">
                      <FileText className="w-3.5 h-3.5 inline mr-1" />
                      Narrative Sections Required
                    </p>
                    <ul className="space-y-1.5">
                      {grant.narrativeSections.map((s) => (
                        <li key={s} className="flex items-start gap-2 text-[12px] text-theme-secondary">
                          <span className="text-purple-500 mt-0.5">•</span>
                          {s}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <p className="text-xs font-bold uppercase tracking-widest text-theme-muted mb-3">
                      Data &amp; Documentation Needed
                    </p>
                    <ul className="space-y-1.5">
                      {grant.dataNeeded.map((d) => (
                        <li key={d} className="flex items-start gap-2 text-[12px] text-theme-secondary">
                          <span className="text-teal-500 mt-0.5">•</span>
                          {d}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Letters of Support */}
                <div className="mb-6">
                  <p className="text-xs font-bold uppercase tracking-widest text-theme-muted mb-3">Letters of Support Required</p>
                  <div className="flex flex-wrap gap-2">
                    {grant.lettersRequired.map((l) => (
                      <span key={l} className="text-xs px-3 py-1.5 rounded-full bg-theme-surface text-theme-secondary border border-theme-subtle">
                        {l}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Past Awards + Effort */}
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="rounded-xl p-4 bg-amber-500/5 border border-amber-500/15">
                    <p className="text-xs font-bold uppercase tracking-widest text-amber-600 dark:text-amber-400 mb-2">Competitive Intelligence</p>
                    <p className="text-[12px] text-theme-secondary leading-relaxed">{grant.pastAwards}</p>
                  </div>
                  <div className="rounded-xl p-4 bg-rose-500/5 border border-rose-500/15">
                    <p className="text-xs font-bold uppercase tracking-widest text-rose-600 dark:text-rose-400 mb-2">Estimated Effort</p>
                    <p className="text-lg font-bold text-rose-600 dark:text-rose-400 mb-1">🔴 HEAVY</p>
                    <p className="text-[12px] text-theme-secondary">{grant.effortHours} total. Includes partnership development (20-25 hrs), data collection (12-15 hrs), narrative writing (25-30 hrs), budget development (10-12 hrs), and internal review (6-10 hrs).</p>
                  </div>
                </div>

                {/* Link */}
                <div className="mt-4 pt-4 border-t border-theme-subtle">
                  <a href={grant.url} target="_blank" rel="noopener noreferrer" className="text-xs text-purple-600 dark:text-purple-400 hover:underline font-mono">
                    {grant.url} →
                  </a>
                </div>
              </div>
            ))}
          </StaggerChildren>
        </div>
      </section>

      {/* ═══════════ E. STRATEGIC GRANTS ═══════════ */}
      <section className="relative py-16 md:py-24 bg-theme-surface/30 print:py-10">
        <div className="max-w-[1200px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <div className="text-center mb-12">
              <span className="overline">Section E · Strategic Grants — Plan Ahead</span>
              <h2
                className="font-heading font-bold text-theme-primary mt-3"
                style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.5rem)' }}
              >
                5 Grants Scoring 6.0–7.0 / 10
              </h2>
              <p className="mt-3 text-theme-secondary max-w-xl mx-auto text-sm">
                Good fit but require partnership development, consortium formation, or strategic pivots. Plan preparation now for future cycles.
              </p>
            </div>
          </AnimateOnScroll>

          <StaggerChildren stagger={80} variant="fade-up" className="space-y-5">
            {strategicGrants.map((grant) => (
              <div key={grant.title} className="card-cosmic rounded-2xl p-6">
                <div className="flex flex-wrap items-start justify-between gap-4 mb-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-2">
                      <TierBadge tier={grant.tier} />
                      <span className="text-xs font-mono text-theme-muted">CFDA {grant.cfda}</span>
                    </div>
                    <h3 className="font-heading font-bold text-lg text-theme-primary leading-snug">{grant.title}</h3>
                    <p className="text-sm text-theme-muted mt-1">{grant.agency}</p>
                  </div>
                  <div className="text-right flex-shrink-0">
                    <div className="text-2xl font-bold font-mono text-amber-600 dark:text-amber-400">{grant.score}</div>
                    <p className="text-xs text-theme-muted">/ 10</p>
                  </div>
                </div>

                {/* Score bars */}
                <div className="grid grid-cols-5 gap-2 mb-4">
                  {[
                    { label: 'Elig.', score: grant.scores.eligibility },
                    { label: 'Align.', score: grant.scores.alignment },
                    { label: 'Award', score: grant.scores.awardSize },
                    { label: 'Comp.', score: grant.scores.competition },
                    { label: 'Time', score: grant.scores.timeline },
                  ].map((dim) => (
                    <div key={dim.label}>
                      <p className="text-[10px] text-theme-muted text-center mb-1">{dim.label}</p>
                      <ScoreBar score={dim.score} color={dim.score >= 8 ? 'teal' : dim.score >= 5 ? 'amber' : 'rose'} />
                      <p className="text-[10px] font-mono text-center mt-0.5 text-theme-secondary">{dim.score}/10</p>
                    </div>
                  ))}
                </div>

                <div className="grid sm:grid-cols-3 gap-3 mb-4">
                  <div className="text-center rounded-lg p-2 bg-theme-surface/50 border border-theme-subtle">
                    <p className="text-[10px] text-theme-muted">Deadline</p>
                    <p className="text-sm font-bold text-theme-primary">{grant.deadline}</p>
                    {grant.daysRemaining !== null && (
                      <p className={`text-[10px] font-semibold ${grant.daysRemaining <= 30 ? 'text-rose-600 dark:text-rose-400' : 'text-theme-muted'}`}>
                        {grant.daysRemaining} days
                      </p>
                    )}
                  </div>
                  <div className="text-center rounded-lg p-2 bg-theme-surface/50 border border-theme-subtle">
                    <p className="text-[10px] text-theme-muted">Est. Award</p>
                    <p className="text-sm font-bold text-purple-600 dark:text-purple-400">{grant.estimatedAward}</p>
                  </div>
                  <div className="text-center rounded-lg p-2 bg-theme-surface/50 border border-theme-subtle">
                    <p className="text-[10px] text-theme-muted">Grants.gov</p>
                    <a href={grant.url} target="_blank" rel="noopener noreferrer" className="text-xs text-purple-600 dark:text-purple-400 hover:underline">
                      View →
                    </a>
                  </div>
                </div>

                <div className="rounded-xl p-4 bg-amber-500/5 border border-amber-500/15">
                  <p className="text-xs font-bold text-amber-600 dark:text-amber-400 mb-1">Strategic Note</p>
                  <p className="text-sm text-theme-secondary leading-relaxed">{grant.keyNote}</p>
                </div>
              </div>
            ))}
          </StaggerChildren>
        </div>
      </section>

      {/* ═══════════ F. MONITOR & SKIP ═══════════ */}
      <section className="relative py-16 md:py-24 print:py-10">
        <div className="max-w-[1200px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <div className="text-center mb-12">
              <span className="overline">Section F · Monitor List &amp; Skip List</span>
              <h2
                className="font-heading font-bold text-theme-primary mt-3"
                style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.5rem)' }}
              >
                13 grants tracked for completeness
              </h2>
            </div>
          </AnimateOnScroll>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Monitor */}
            <AnimateOnScroll variant="fade-up">
              <div className="card-cosmic rounded-2xl p-6">
                <div className="flex items-center gap-3 mb-5">
                  <Eye className="w-5 h-5 text-blue-500" />
                  <p className="font-heading font-bold text-lg text-theme-primary">Monitor List — 8 Grants</p>
                </div>
                <div className="space-y-4">
                  {monitorGrants.map((g) => (
                    <div key={g.title} className="border-b border-theme-subtle/50 pb-3 last:border-0 last:pb-0">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <p className="text-[13px] font-semibold text-theme-primary leading-snug">{g.title}</p>
                          <p className="text-[11px] text-theme-muted">{g.agency} · {g.deadline}</p>
                        </div>
                        <span className="text-xs font-bold font-mono text-blue-600 dark:text-blue-400 flex-shrink-0">{g.score}</span>
                      </div>
                      <p className="text-[11px] text-theme-tertiary mt-1 leading-relaxed">{g.note}</p>
                    </div>
                  ))}
                </div>
              </div>
            </AnimateOnScroll>

            {/* Skip */}
            <AnimateOnScroll variant="fade-up" delay={100}>
              <div className="card-cosmic rounded-2xl p-6">
                <div className="flex items-center gap-3 mb-5">
                  <SkipForward className="w-5 h-5 text-gray-400" />
                  <p className="font-heading font-bold text-lg text-theme-primary">Skip List — 5 Grants</p>
                </div>
                <div className="space-y-4">
                  {skipGrants.map((g) => (
                    <div key={g.title} className="border-b border-theme-subtle/50 pb-3 last:border-0 last:pb-0">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <p className="text-[13px] font-semibold text-theme-primary leading-snug">{g.title}</p>
                          <p className="text-[11px] text-theme-muted">{g.agency}</p>
                        </div>
                        <span className="text-xs font-bold font-mono text-gray-400 flex-shrink-0">{g.score}</span>
                      </div>
                      <p className="text-[11px] text-theme-tertiary mt-1 leading-relaxed">{g.reason}</p>
                    </div>
                  ))}
                </div>

                {/* Additional context */}
                <div className="mt-6 rounded-xl p-4 bg-theme-surface/50 border border-theme-subtle">
                  <p className="text-xs font-bold text-theme-muted mb-2">Why these were reviewed</p>
                  <p className="text-[11px] text-theme-tertiary leading-relaxed">
                    The pipeline searches Grants.gov using keyword matching against Valencia&apos;s program portfolio. Some results (Tribal programs, basic research) appear due to keyword overlap but are not viable. Including them provides transparency into the full search scope.
                  </p>
                </div>
              </div>
            </AnimateOnScroll>
          </div>
        </div>
      </section>

      {/* ═══════════ G. DEADLINE CALENDAR ═══════════ */}
      <section className="relative py-16 md:py-24 bg-theme-surface/30 print:py-10">
        <div className="max-w-[1000px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <div className="text-center mb-12">
              <span className="overline">Section G · Deadline Calendar</span>
              <h2
                className="font-heading font-bold text-theme-primary mt-3"
                style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.5rem)' }}
              >
                Which grants to pursue when
              </h2>
            </div>
          </AnimateOnScroll>

          <AnimateOnScroll variant="fade-up" delay={80}>
            <div className="card-cosmic rounded-2xl overflow-hidden">
              {deadlineCalendar.map((item, idx) => (
                <div
                  key={item.grant}
                  className={`p-5 ${idx < deadlineCalendar.length - 1 ? 'border-b border-theme-subtle' : ''}`}
                >
                  <div className="flex flex-wrap items-start gap-4">
                    <div className="flex-shrink-0 w-20">
                      <p className="font-mono text-sm font-bold text-theme-primary">{item.month}</p>
                      {item.daysRemaining !== null && (
                        <p className={`text-[10px] font-semibold ${item.daysRemaining <= 30 ? 'text-rose-600 dark:text-rose-400' : item.daysRemaining <= 100 ? 'text-amber-600 dark:text-amber-400' : 'text-theme-muted'}`}>
                          {item.daysRemaining}d left
                        </p>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-semibold text-theme-primary">{item.grant}</p>
                      <p className="text-xs text-theme-muted mt-0.5">{item.deadline}</p>
                      <p className="text-xs text-theme-secondary mt-1">{item.action}</p>
                    </div>
                    <div className="flex-shrink-0">
                      <TierBadge tier={item.tier} />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </AnimateOnScroll>
        </div>
      </section>

      {/* ═══════════ H. ACTION PLAN ═══════════ */}
      <section className="relative py-16 md:py-24 print:py-10">
        <div className="max-w-[1200px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <div className="text-center mb-12">
              <span className="overline">Section H · Recommended Action Plan</span>
              <h2
                className="font-heading font-bold text-theme-primary mt-3"
                style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.5rem)' }}
              >
                Implementation Roadmap
              </h2>
            </div>
          </AnimateOnScroll>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                timeline: 'Apply NOW (Next 30-60 Days)',
                color: 'rose',
                icon: '🚨',
                actions: [
                  { title: 'ETA Strengthening CC Grants — convene leadership, select industry sectors, begin consortium formation', effort: 'High', impact: 'High', revenue: '$1-3M over 3-4 years' },
                  { title: 'NASA Aerospace Hubs — GO/NO-GO decision within 5-7 days. Skip unless existing aerospace relationships exist', effort: 'High', impact: 'Medium', revenue: 'Up to $1.5M' },
                ],
              },
              {
                timeline: 'Plan for Next Quarter',
                color: 'purple',
                icon: '📋',
                actions: [
                  { title: 'NSF ATE — begin preparation April 2026. Select IT/cyber, healthcare tech, or manufacturing focus', effort: 'High', impact: 'High', revenue: '$300K-$900K over 3 years' },
                  { title: 'MSIPP — confirm HSI status, identify 2-3 MSI consortium partners, initiate NNSA lab contact', effort: 'High', impact: 'Medium', revenue: '$500K-$1.5M over 3-5 years' },
                  { title: 'ONR STEM — develop NAWCTSD partnership (located in Orlando), emphasize cybersecurity for naval operations', effort: 'Medium', impact: 'Medium', revenue: 'Unknown' },
                ],
              },
              {
                timeline: 'Explore Additionally',
                color: 'teal',
                icon: '🔭',
                actions: [
                  { title: 'Florida Job Growth Grant Fund — state competitive grants for healthcare, IT, manufacturing', effort: 'Medium', impact: 'High', revenue: 'State funding' },
                  { title: 'Corporate Foundations — cultivate Lockheed Martin, Northrop Grumman, AdventHealth, Orlando Health', effort: 'Low', impact: 'Medium', revenue: 'Varies' },
                  { title: 'CareerSource Central Florida — maintain WIOA partnership for dislocated worker and training funding', effort: 'Low', impact: 'Medium', revenue: 'Formula funding' },
                ],
              },
            ].map((tier) => (
              <AnimateOnScroll key={tier.timeline} variant="fade-up" delay={80}>
                <div className="card-cosmic rounded-2xl p-6 h-full flex flex-col">
                  <div className="mb-5">
                    <span className="text-2xl">{tier.icon}</span>
                    <h3 className={`font-heading font-bold text-base mt-2 ${
                      tier.color === 'rose' ? 'text-rose-600 dark:text-rose-400'
                      : tier.color === 'purple' ? 'text-purple-600 dark:text-purple-400'
                      : 'text-teal-600 dark:text-teal-400'
                    }`}>
                      {tier.timeline}
                    </h3>
                  </div>
                  <div className="space-y-4 flex-1">
                    {tier.actions.map((action, j) => (
                      <div key={j} className="rounded-lg p-3.5 bg-theme-surface/50 border border-theme-subtle">
                        <p className="text-[12px] font-semibold text-theme-primary leading-snug mb-1.5">{action.title}</p>
                        <div className="flex flex-wrap gap-1.5 mb-1.5">
                          <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${
                            action.effort === 'Low' ? 'bg-teal-500/10 text-teal-700 dark:text-teal-400'
                            : action.effort === 'Medium' ? 'bg-amber-500/10 text-amber-700 dark:text-amber-400'
                            : 'bg-rose-500/10 text-rose-700 dark:text-rose-400'
                          }`}>
                            Effort: {action.effort}
                          </span>
                          <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${
                            action.impact === 'High' ? 'bg-purple-500/10 text-purple-700 dark:text-purple-400'
                            : 'bg-blue-500/10 text-blue-700 dark:text-blue-400'
                          }`}>
                            Impact: {action.impact}
                          </span>
                        </div>
                        <p className="text-[10px] text-teal-600 dark:text-teal-400 font-semibold">{action.revenue}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </AnimateOnScroll>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════ I. METHODOLOGY ═══════════ */}
      <section className="relative py-16 md:py-20 bg-theme-surface/30 print:py-10">
        <div className="max-w-[900px] mx-auto px-6">
          <AnimateOnScroll variant="fade-up">
            <span className="overline block text-center mb-3">Section I · Methodology</span>
            <h2
              className="font-heading font-bold text-theme-primary text-center mb-10"
              style={{ fontSize: 'clamp(1.5rem, 2.5vw + 0.5rem, 2.25rem)' }}
            >
              How This Report Was Generated
            </h2>
          </AnimateOnScroll>

          <div className="grid md:grid-cols-2 gap-6">
            <AnimateOnScroll variant="fade-up" delay={80}>
              <div className="card-cosmic rounded-2xl p-6">
                <p className="text-xs font-bold uppercase tracking-widest text-theme-muted mb-4">
                  Live Pipeline Process
                </p>
                <ul className="space-y-4">
                  {[
                    {
                      step: 'Step 1: Grant Discovery',
                      desc: 'Searched Grants.gov API using keywords derived from Valencia\'s program portfolio (workforce development, community college, STEM, healthcare, IT, manufacturing). Retrieved 20 active federal opportunities.',
                    },
                    {
                      step: 'Step 2: AI Fit Scoring',
                      desc: 'Each grant scored on 5 dimensions (eligibility fit, strategic alignment, award size, competition level, timeline feasibility) using Valencia\'s institutional profile. Composite score weighted by dimension importance.',
                    },
                    {
                      step: 'Step 3: Deep Analysis',
                      desc: 'Priority and strategic grants received full analysis: application requirements, narrative sections, data needed, letters of support, competitive intelligence, effort estimates, and specific fit rationale.',
                    },
                    {
                      step: 'Step 4: Report Generation',
                      desc: 'Grants tiered into Priority (8.0+), Strategic (6.0-7.9), Monitor (4.0-5.9), Skip (<4.0). 9,549-word report with deadline calendar and action recommendations.',
                    },
                  ].map((item) => (
                    <li key={item.step} className="flex items-start gap-3">
                      <span className="text-[11px] font-bold text-purple-600 dark:text-purple-400 pt-0.5 flex-shrink-0 w-36">{item.step}</span>
                      <span className="text-[12px] text-theme-secondary leading-snug">{item.desc}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </AnimateOnScroll>

            <AnimateOnScroll variant="fade-up" delay={160}>
              <div className="card-cosmic rounded-2xl p-6">
                <p className="text-xs font-bold uppercase tracking-widest text-theme-muted mb-4">
                  Data Sources &amp; Scoring Model
                </p>
                <ul className="space-y-3">
                  {[
                    { source: 'Grants.gov API', desc: '20 federal grant opportunities retrieved and parsed — titles, agencies, deadlines, CFDA codes, descriptions' },
                    { source: 'Institutional Profile', desc: 'Valencia College — public community college, Orlando FL, 75K+ students, programs in healthcare, IT, manufacturing, hospitality' },
                    { source: 'Fit Score Model', desc: '5 dimensions × 10-point scale: Eligibility (weight: 25%), Alignment (25%), Award Size (20%), Competition (15%), Timeline (15%)' },
                    { source: 'Tier Thresholds', desc: 'Priority ≥ 8.0, Strategic 6.0-7.9, Monitor 4.0-5.9, Skip < 4.0' },
                    { source: 'Competitive Intel', desc: 'Past award research, typical award ranges, success factors, and application strategy derived from program documentation' },
                  ].map((item) => (
                    <li key={item.source} className="flex items-start gap-3">
                      <span className="text-[11px] font-bold text-teal-600 dark:text-teal-400 pt-0.5 flex-shrink-0 w-32">{item.source}</span>
                      <span className="text-[12px] text-theme-secondary leading-snug">{item.desc}</span>
                    </li>
                  ))}
                </ul>

                <div className="mt-6 rounded-xl p-4 bg-teal-500/5 border border-teal-500/15">
                  <p className="text-xs font-bold text-teal-600 dark:text-teal-400 mb-2">Pipeline Metadata</p>
                  <div className="grid grid-cols-2 gap-2 text-[11px] text-theme-secondary">
                    <p>Grants Reviewed: <span className="font-mono font-bold">20</span></p>
                    <p>Report Words: <span className="font-mono font-bold">9,549</span></p>
                    <p>Generated: <span className="font-mono font-bold">Feb 19, 2026</span></p>
                    <p>Pages: <span className="font-mono font-bold">~20</span></p>
                  </div>
                </div>
              </div>
            </AnimateOnScroll>
          </div>
        </div>
      </section>

      {/* ═══════════ J. CTA ═══════════ */}
      <section className="relative py-20 md:py-28 print:py-10">
        <div className="max-w-[800px] mx-auto px-6 text-center">
          <AnimateOnScroll variant="fade-up">
            <span className="overline">Ready to Find Your Funding?</span>
            <h2
              className="font-heading font-bold text-theme-primary mt-4"
              style={{ fontSize: 'clamp(1.75rem, 3vw + 0.5rem, 2.75rem)' }}
            >
              Get a Grant Intelligence Scan for your institution
            </h2>
            <p className="mt-4 text-theme-secondary text-lg leading-relaxed">
              We scan federal, state, and foundation grants against your program portfolio — then deliver a scored, tiered pursuit list with application requirements, competitive intelligence, and an action-ready deadline calendar.
            </p>

            <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Link href="/grants">
                <button className="btn-cosmic btn-cosmic-primary text-sm py-3 px-7">
                  Order Grant Intelligence Scan
                  <ArrowRight className="ml-2 h-4 w-4" />
                </button>
              </Link>
            </div>

            <div className="mt-10 card-cosmic rounded-2xl p-6 text-left">
              <p className="font-heading font-bold text-lg text-theme-primary mb-3">What You Receive</p>
              <ul className="space-y-2 text-sm text-theme-secondary leading-relaxed">
                {[
                  'Full federal grant landscape scan — 20+ opportunities scored against your institution',
                  'AI-powered fit scoring on 5 dimensions (eligibility, alignment, award size, competition, timeline)',
                  'Priority tier classification — which grants to pursue now vs. plan for later',
                  'Deep-dive analysis on priority grants — application requirements, narrative sections, data needed',
                  'Competitive intelligence — past awards, success factors, typical award ranges',
                  'Effort estimates with hour breakdowns for each priority grant',
                  'Deadline calendar with days-remaining countdown and action items',
                  'Implementation roadmap — what to do this week, this quarter, and this year',
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2.5">
                    <CheckCircle2 className="h-4 w-4 text-theme-muted flex-shrink-0 mt-0.5" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </AnimateOnScroll>
        </div>
      </section>
    </div>
  );
}
