#!/bin/bash

echo "🔄 Running Database Migrations..."
echo ""
echo "To run these migrations, you need to:"
echo "1. Log into your Supabase project at https://supabase.com/dashboard"
echo "2. Go to SQL Editor"
echo "3. Run each migration file in order:"
echo ""
echo "   a) supabase/schema.sql (if not already run)"
echo "   b) supabase/migrations/001_add_api_cache.sql"
echo "   c) supabase/migrations/002_disable_rls_for_testing.sql"
echo ""
echo "Or, if you have Supabase CLI installed:"
echo "   supabase db push"
echo ""
echo "📋 Migration files are located in:"
echo "   - supabase/schema.sql"
echo "   - supabase/migrations/"
